version: "3.9"

services:
  discord-bot:
    build: .
    container_name: discord_bot
    volumes:
      - tu carpeta local donde descargaste el repo :/app
    working_dir: /app
    command: python bot/bot.py
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN= token del bot
